### ISSUE TITLE
[Enhancement] Agregar versión de la librería

### ISSUE THREAD

**Issue by javatlacati** [LanyuEStudio/lanyu-ui#2]
Creo que se puede agregar la versión en el gradle builld. Al menos en maven es en el pom.

Sugiero versionado semántico.

**Comment by Awes0meM4n** [comment]
Buena idea, añado información del proyecto a `build.gradle`. Lo cerraré con el próximo commit con otras mejoras:
```
group = 'es.lanyu'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'
```
